### ISSUE TITLE
Decide+document structure for implementing RFCs

### ISSUE THREAD

**Issue by dstansby** [BioImageTools/ome-zarr-models-py#21]
If someone has an RFC and want's to implement it here, what should they do? A new branch? A new pull request? Do we want a new namespace for RFCs?

**Comment by d-v-b** [comment]
I don't think an RFC namespace would work well, since our namespaces names should probably convey content and `rfc{index}` fails there. For implementing RFCs I'd say that branch + PR workflow is the way to go, and if people try to open multiple PRs to implement the same RFC we can have a conversation about coordinating it, like any other feature.
